#!/bin/sh -e
apt-get update
apt-get install -y libgeos-dev git wget

VERSION=1.2.2
OS=linux
ARCH=amd64

GOTAR=go$VERSION.$OS-$ARCH.tar.gz
GOTARURL=http://golang.org/dl/$GOTAR

if [ ! -f /tmp/$GOTAR ]; then
  wget $GOTARURL -O /tmp/$GOTAR
fi
tar -C /usr/local -xzf /tmp/$GOTAR

echo "Make sure to put go on your path:"
echo "  export PATH=\$PATH:/usr/local/go/bin"
