#!/bin/bash

set -e
set -x

export GOBIN=${PWD}/bin
export GOPATH=${PWD}/gopath
export PATH=${PATH}:/usr/local/go/bin:${GOBIN}

rm -rf bin
rm -rf gopath
mkdir -p gopath/src/github.com/azavea/ecobenefits
cp main.go gopath/src/github.com/azavea/ecobenefits
cp -r eco gopath/src/github.com/azavea/ecobenefits/eco
go get -v github.com/azavea/ecobenefits
go get -v github.com/tools/godep

go clean
godep restore
godep go test eco/*
go install github.com/azavea/ecobenefits
cp -r data bin/data
cp config.gcfg.template bin
rm bin/godep

cd bin && tar czf ecoservice.tar.gz --transform 's|^|ecoservice/|' *
